### ISSUE TITLE
Issue with software-properties (both the kde gui and the cli tool 'add-apt-repository')

### ISSUE THREAD

**Issue by h4ndshake** [nomad-desktop/nxos-base-files#1]
The issue seems related with the lsb-release file

> Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 114, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 607, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for nxos/nxos

Hope it gets fixed, thanks in advance

**Comment by UriHerrera** [comment]
The script that Ubuntu uses to add PPAs to the system is made specifically for Ubuntu releases that's why it's failing. You can add the PPA manually:

- Create a blank file in '/etc/apt/sources.list.d/PPA_NAME'
- Edit the file and add the URL of the PPA: 
![image](https://user-images.githubusercontent.com/3053525/27819304-3797c068-605f-11e7-9fa6-ac2bbcef4a45.png) _We're using artful but you might want to change that to something else._
- Save the file and on terminal do: 'sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys PPA_PUB_KEY'
![image](https://user-images.githubusercontent.com/3053525/27819381-96322348-605f-11e7-91a6-1b5cdd932137.png) 
_The key are the last 8 digits._
- Run 'sudo apt update'

**Comment by h4ndshake** [comment]
This problem isn't related ONLY with add-apt-repository

this happens when trying to open software-properties-kde for managing gpg keys, repos and drivers too..
